config/routes.rb
Rails.application.routes.draw do

  root :to => 'main#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get '/login', :to => 'sessions#new', :as => 'login'
  post '/login', :to => 'sessions#create'
  delete '/logout', :to => 'sessions#destroy'


  namespace :admin do
    resources :dashboard, only: [:index]
    resources :items, only: [:index, :edit, :new, :create, :update]
    resources :analytics, only: [:index]
  end


  resources :users , only: [:new, :create, :edit, :update]

  resources :orders, only: [:index, :new, :show, :update]

  resources :dashboard, only: [:index]

  get '/cart', :to => 'carts#index', :as => 'cart'

  resources :items, only: [:index, :show]

  resources :carts, only: [:index, :create, :destroy]

  patch '/cart', :to => 'carts#update'

  delete '/cart', :to => 'carts#destroy'
  resources :carts, only: [:index, :create, :destroy]

  get '/:category', to: 'categories#show', param: :slug, as: "category"

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
before_action :require_admin
  def index
    if params[:status] == "ordered" || params[:status] == "paid" || params[:status] == "cancelled" || params[:status] == "completed"
      @orders = Order.filter_by_status(params[:status])
    else
      @orders = Order.all
    end
    flash[:notice] = "You're logged in as an Administrator."
  end

end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
before_action :require_admin
  def index
  
    @admin = User.find(current_user.id)
  end

private
  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    if current_user.nil?
      redirect_to login_path
    else
      @user = User.find(current_user.id)
    end
  end

end

app/views/admin/dashboard/index.html.erb
<div class="container">
  <h3>Admin Dashboard</h3>
  <nav class="nav nav-tabs" id="myTab" role="tablist">
    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-expanded="true">View Orders</a>
    <%= link_to "View Items", admin_items_path, class: "nav-item nav-link" %>
    <%= link_to "Update Account", edit_user_path(current_user), class: "nav-item nav-link" %>
    <%= link_to "View Analytics", admin_analytics_path, class: "nav-item nav-link" %>

    </div>
  </nav>
  <div class="container">
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <div id="right">
        <div class="dropdown">
          <button class="badge badge-danger dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Filter Orders
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <% Order.count_by_status.each do |status, count| %>
            <li><%= link_to status.capitalize, admin_dashboard_index_path(status: status) %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'View all', admin_dashboard_index_path %></li>
          </ul>
        </div>
      </div>
 			 <!-- <%= link_to "All Orders", admin_dashboard_index_path, class: "badge badge-success" %>
 			 <%= link_to "All Items", admin_items_path, class: "badge badge-success" %> -->
 	      <table class="table table-hover">
 	         <thead>
 	            <tr>
         	      <th>Order #</th>
         	      <th>Order Placed</th>
         	      <th>Order Status</th>
 		      			<th></th>
 		      			<th></th>
 	            </tr>
 	          </thead>
             <tbody>
               <% @orders.each do |order| %>
                 <tr class="order-<%= order.id %>">
                   <th scope="row">
                     <%= link_to order.id, order_path(order) %>
                   </th>
                   <td><%= order.date %></td>
                   <td class="status"><%= order.status.capitalize %></td>
                   <td><%= link_to "Cancel", order_path(order, status: "cancelled"), method: :put, class: "badge badge-warning" if order.status == "paid" || order.status == "ordered" %></td>
                   <% if order.status == "ordered" %>
                     <td><%= link_to "Mark as Paid", order_path(order, status: "paid"), method: :put, class: "badge badge-success" %></td>
                   <% elsif order.status == "paid" %>
                     <td><%= link_to "Mark as Completed", order_path(order, status: "completed"), method: :put, class: "badge badge-success" %></td>
                   <% else %>
                     <td></td>
                   <% end %>
                 </tr>
             <% end %>
           </tbody>
       </table>
     </div>
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">...</div>
    <div class="tab-pane fade" id="nav-dropdown1" role="tabpanel" aria-labelledby="nav-dropdown1-tab">...</div>
    <div class="tab-pane fade" id="nav-dropdown2" role="tabpanel" aria-labelledby="nav-dropdown2-tab">...</div>
  </div>
</div>