config/routes.rb
Rails.application.routes.draw do

  root :to => 'main#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get '/login', :to => 'sessions#new', :as => 'login'
  post '/login', :to => 'sessions#create'
  delete '/logout', :to => 'sessions#destroy'


  namespace :admin do
    resources :dashboard, only: [:index]
    resources :items, only: [:index, :edit, :new, :create, :update]
    resources :analytics, only: [:index]
  end


  resources :users , only: [:new, :create, :edit, :update]

  resources :orders, only: [:index, :new, :show, :update]

  resources :dashboard, only: [:index]

  get '/cart', :to => 'carts#index', :as => 'cart'

  resources :items, only: [:index, :show]

  resources :carts, only: [:index, :create, :destroy]

  patch '/cart', :to => 'carts#update'

  delete '/cart', :to => 'carts#destroy'
  resources :carts, only: [:index, :create, :destroy]

  get '/:category', to: 'categories#show', param: :slug, as: "category"

end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def total_count
    contents.values.sum
  end

  def add_item(id)
    contents[id.to_s] = (contents[id.to_s] || 0) + 1
  end

  def decrease_quantity(id)
    if contents[id.to_s] > 0
      contents[id.to_s] -=1
    end
    if contents[id.to_s] == 0
      delete_item(id)
    end
  end

  def increase_quantity(id)
    contents[id.to_s] += 1
  end

  def count_of(id)
    contents[id.to_s].to_i
  end

  def item_and_quantity
    items = {}
    contents.each do |item_id, quantity|
      items[Item.find(item_id)] = quantity
    end
    items
  end

  def delete_item(id)
    contents.delete(id.to_s)
  end

  def destroy
    @contents.clear
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def index
    @items = @cart.item_and_quantity
  end

  def create
    item = Item.find(params[:item_id])
    @cart.add_item(item.id)
    session[:cart] = @cart.contents
    flash[:notice] = "You now have #{pluralize(@cart.count_of(item.id), item.title)}."
    redirect_back(fallback_location: root_path)
  end

  def update
    item_id = params[:id]
    if params[:condition] == "decrease"
      @cart.decrease_quantity(item_id)
      if @cart.contents[item_id].nil?
        flash[:successfully_removed] = "Successfully removed <a href=#{item_path(item_id)}>#{Item.find(item_id).title}</a> from your cart."
      end
    elsif params[:condition] == "increase"
      @cart.increase_quantity(item_id)
    end
    redirect_to cart_path
  end

  def destroy
    item = Item.find(params[:id])
    @cart.delete_item(item.id)
    flash[:successfully_removed] = "Successfully removed <a href=#{item_path(item)}>#{item.title}</a> from your cart."
    redirect_back(fallback_location: root_path)
  end

  def post
  end

end

app/views/carts/index.html.erb
<style>
    .cart_image{
      width: 3em;
      height: 4em;
    }

      .checkout{
        text-align: right;
        margin-left: auto;
        margin-right: auto;
      }

      .total{
        text-align: right;
        margin-left: auto;
        margin-right: auto;
      }

    h2{
      text-align: center;
      font-size: 3em;
    }
</style>
<div class="container">
    <% if current_user  %>
        <h3> <%= current_user.first_name %>'s  Cart</h3>
    <% else %>
        <h3> Your Cart </h3>
    <% end %>
    <h6><%= link_to "Continue Shopping", items_path %></h6>
	<center>
	<!-- <div class="col-10"> -->
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th>Name</th>
        <th></th>
        <th>Price</th>
        <th>Quantity</th>
        <th></th>
        <th></th>
        <th>Subtotal</th>
	    </tr>
      <tbody>

    <% @items.each do |item, quantity| %>
      <div class="item-#{item.id}">
        <tr>
        <th scope="row"><strong><%= link_to item.title, item_path(item) %></strong></th>
        <td><%= image_tag item.image, :class => "cart_image"%></td>
        <td>$<%= item.price %></td>
        <td><%= quantity %></td>
        <td><%= link_to "-", cart_path(id: item.id, condition: "decrease"), action: :update, method: :patch, class: "badge badge-danger" %>
        <%= link_to "+", cart_path(id: item.id, condition: "increase"), action: :update, method: :patch, class: "badge badge-success" %></td>
        <td><%= link_to "Remove", cart_path(id: item.id), method: :delete, class: "badge badge-danger" %></td>
        <td>$<%= quantity * item.price %></td>
      </tr>
      </div>
      <% end %>
    </tbody>
    </table>
    <div class="total">
      <% sum = 0 %>
      <% @items.each do |item, quantity| %>
      <% sum += (item.price * quantity) %>
      <% end %>
      <p><b>Total: $<%= sum %></b></p>
    </div>
    <div class="checkout">
      <% if current_user %>
        <%= link_to "Checkout", new_order_path%>
      <% else %>
        <%= link_to "Login", login_path %> <br />
        <%= link_to "Create new account", new_user_path %>
      <% end %>
    </div>
  <!-- </div> -->
</center>
</div>