config/routes.rb
Rails.application.routes.draw do

  root :to => 'main#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get '/login', :to => 'sessions#new', :as => 'login'
  post '/login', :to => 'sessions#create'
  delete '/logout', :to => 'sessions#destroy'


  namespace :admin do
    resources :dashboard, only: [:index]
    resources :items, only: [:index, :edit, :new, :create, :update]
    resources :analytics, only: [:index]
  end


  resources :users , only: [:new, :create, :edit, :update]

  resources :orders, only: [:index, :new, :show, :update]

  resources :dashboard, only: [:index]

  get '/cart', :to => 'carts#index', :as => 'cart'

  resources :items, only: [:index, :show]

  resources :carts, only: [:index, :create, :destroy]

  patch '/cart', :to => 'carts#update'

  delete '/cart', :to => 'carts#destroy'
  resources :carts, only: [:index, :create, :destroy]

  get '/:category', to: 'categories#show', param: :slug, as: "category"

end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :category
	has_many :order_items
	has_many :orders, through: :order_items
	validates :title     ,  presence: true, uniqueness: true
	validates :description, :price, presence: true
	has_attached_file :image,
	:default_url => '/images/missing.jpg', styles: {thumb: "68x68#", medium: "300x300#"},
	:path => ":rails_root/public/images/:id/:style/:filename",
  :url => "/images/:id/:style/:filename"
	validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/jpg', 'image/gif', 'image/png']
	enum condition: ["active", "retired"]


	def self.total_sold_by_item
		group(:title).joins(:order_items).sum(:quantity)
	end

	def self.items_by_title_with_status
		group(:title).joins(:orders).group(:status).count
	end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
before_action :require_admin
  def index
    @items = Item.all
  end
	
	def new
    @item = Item.new
	end
  
  def create
    @categories = Category.all
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      render :new
    end
  end
  
  def update
    @categories = Category.all
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      render :edit
    end
  end
  
  def edit
    @item = Item.find(params[:id])
  end

	private
  
  def item_params
    params.require(:item).permit(:title, :description, :price, :image, :category_id)
  end
  
	def require_admin
		render file: "/public/404" unless current_admin?
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end
end

app/views/items/index.html.erb
<!DOCTYPE html>
<head>
	<meta charset="utf-8">
	<title>Shop</title>
</head>
<body>

<div class="container">
	<div class="row">
		<% @items.each do |item| %>
		<div class="center-block">
			<div class="card border-white" style="width: 15rem;">
				<%= image_tag item.image.url, size: "250" %>
				<div class="card-body">
				<center><p><strong><%= link_to item.title, item_path(item) %></strong></p>
				<!-- <p>Description: <%= item.description %></p> -->
				<p>Price: $<%= item.price %></p>
				<% unless item.retired? %>
				<%= link_to "Add to cart", carts_path(item_id: item.id), method: :post, class: "badge badge-primary" %></center>
				<% else %>
				<div class="badge badge-secondary">
					Retired
				</div>
				<% end %>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>

</body>

app/views/items/show.html.erb
<!DOCTYPE html>
<head>
	<meta charset="utf-8">
	<title><%= @item.title %></title>
</head>
<body>
	<div class = "container">
	<h4><%= link_to "Continue shopping", items_path %></h4>
		<div class="row text-center">
			<div class='col-6'>
				<%= image_tag @item.image  %>
				</div>
			<div class='col-6 card bg-info'>
				<div class='card-body '>
				<h2><strong><%= @item.title %></strong></h2> <br />
				<%= @item.description %> <br /> <br />
				Price:$ <%= @item.price %> <br />
				<% unless @item.retired? %>
				<%= link_to "Add to cart", carts_path(item_id: @item.id), method: :post, class: "badge badge-primary" %></center>
				<% else %>
				<div class="badge badge-secondary">
					Retired
				</div>
				<% end %>
				</div>
			</div>
		</div>
	</div>

</body>