config/routes.rb
Rails.application.routes.draw do

  root :to => 'main#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get '/login', :to => 'sessions#new', :as => 'login'
  post '/login', :to => 'sessions#create'
  delete '/logout', :to => 'sessions#destroy'


  namespace :admin do
    resources :dashboard, only: [:index]
    resources :items, only: [:index, :edit, :new, :create, :update]
    resources :analytics, only: [:index]
  end


  resources :users , only: [:new, :create, :edit, :update]

  resources :orders, only: [:index, :new, :show, :update]

  resources :dashboard, only: [:index]

  get '/cart', :to => 'carts#index', :as => 'cart'

  resources :items, only: [:index, :show]

  resources :carts, only: [:index, :create, :destroy]

  patch '/cart', :to => 'carts#update'

  delete '/cart', :to => 'carts#destroy'
  resources :carts, only: [:index, :create, :destroy]

  get '/:category', to: 'categories#show', param: :slug, as: "category"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Little Shop Of Funsies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <style>
    .successfully_removed {
            color: green;
    }
    .alert{
      margin-left: auto;
      margin-right: auto;
      width: auto;
      height: auto;
      text-align: center;
    }
    h1 {
            font-family: 'Pacifico', cursive;
            font-size: 65px;
    }
    div.container {
              width:800px;
              height:auto;
              padding: 5px;
      }

    a {
            color: black;
        }
    .center-block {
            display: block;
            margin-right: auto;
            margin-left: auto;
    }

    #left {
      text-align: left;
      float: left;
    }
    #right {
      text-align: right;
      /* Change this to whatever the width of your left column is*/
    }
    .clear {
      clear: both;
    }

    </style>
  </head>

  <body>
    <ul class="nav justify-content-center">
      <% if current_user.nil? %>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: "nav-link active" %>
        </li>
      <% end %>
      <% if current_user && current_user.admin? %>
        <li class="nav-item">
          <%= link_to 'Dashboard', admin_dashboard_index_path, class: "nav-link active" %>
        </li>
      <% elsif current_user %>
        <li class="nav-item">
          <%= link_to 'Dashboard', dashboard_index_path, class: "nav-link active" %>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_path, class: "nav-link active" %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Items', items_path, class: "nav-link active" %>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Categories</a>
          <div class="dropdown-menu">
            <% @categories.each do |category| %>
            <%= link_to category.title, category_path(category.slug), class: "dropdown-item" %>
            <% end %>
          </div>
      </li>
      <li class="nav-item">
        <%= link_to 'Cart', carts_path, class: "btn" %>
        <span class="badge badge-secondary"><%= @cart.total_count %></span>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link active" %>
        </li>
      <% end %>

    </ul>
    <% if flash.count > 0  %>
    <div class="center-block" style= "width: 15rem;">
    <div class="alert alert-primary alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <% end  %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, raw(msg), class: name %>
      <% end %>
    </div>
    </div>
    <div class="container">
      <div class="title">
        <center>
          <h1>Little Shop Of Funsies</h1><br />
          <%= link_to (image_tag ('house-of-funsies-banner.png')), root_path %>
        </center>
      </div>
    </div>
    <%= yield %>
  </body>
</html>